<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Microsoft.Maui.Controls" Version="$(MauiVersion)"/>
        <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="$(MauiVersion)"/>
        <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.9"/>
        <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.9"/>
        <PackageVersion Include="Shiny.Mediator" Version="6.6.1"/>
        <PackageVersion Include="Shiny.Mediator.Maui" Version="6.6.1"/>
        <PackageVersion Include="Shiny.Notifications" Version="5.0.0-beta-0137"/>
        <PackageVersion Include="Shiny.Notifications.Linux" Version="5.0.0-beta-0137"/>
        <PackageVersion Include="Shiny.Blazor.Controls" Version="1.0.1-beta-0112"/>
        <PackageVersion Include="Shiny.Maui.Controls.Desktop" Version="1.0.1-beta-0112"/>
        <PackageVersion Include="Shiny.DocumentDb.Sqlite" Version="7.1.1"/>
        <PackageVersion Include="Shiny.DocumentDb.Extensions.DependencyInjection" Version="7.1.1"/>
        <PackageVersion Include="Shiny.Extensions.Stores" Version="5.0.0"/>
        <PackageVersion Include="Shiny.Extensions.DependencyInjection" Version="5.0.0"/>
        <PackageVersion Include="Platform.Maui.MacOS" Version="0.3.0"/>
        <PackageVersion Include="Platform.Maui.MacOS.Essentials" Version="0.3.0"/>
        <PackageVersion Include="Platform.Maui.MacOS.BlazorWebView" Version="0.3.0"/>
        <PackageVersion Include="Platform.Maui.Linux.Gtk4" Version="0.6.0"/>
        <PackageVersion Include="Platform.Maui.Linux.Gtk4.Essentials" Version="0.6.0"/>
        <PackageVersion Include="Platform.Maui.Linux.Gtk4.BlazorWebView" Version="0.6.0"/>
        <PackageVersion Include="Octokit" Version="14.0.0"/>
    </ItemGroup>
</Project>